FROM python:3.10

WORKDIR /pytapp

COPY requirements/backend.in requirements/
COPY spaceship/app.py spaceship/

RUN pip install -r requirements/backend.in

COPY . . 

CMD [ "uvicorn" , "spaceship.main:app" , "--host=0.0.0.0" , "--port=8080" ]